### ISSUE TITLE
Project defunct?

### ISSUE THREAD

**Issue by domxch** [MotazSabri/Hanami-release#10]
Every time I tried Hanami for the last few months it just always says Getting ready, polishing flowers but never starts...

**Comment by MotazSabri** [comment]
@domxch 
Thanks for your kind follow-up. 
The Translation service API was updated to match the backend latest modifications. I created a new release that you may find it [here](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.7/Hanami.Installer.exe).

Thanks for using Hanami,

**Comment by domxch** [comment]
Yep that works - thanks!
