### ISSUE TITLE
Works well, but hoping the speed can be improved.

### ISSUE THREAD

**Issue by MidnightKittenCat** [MotazSabri/Hanami-release#11]
It works well for my needs however the speed of it is making me want to look at other options, is there any way this can be sped up?

**Comment by MotazSabri** [comment]
> It works well for my needs however the speed of it is making me want to look at other options, is there any way this can be sped up?

Thank you for reaching out and providing valuable feedback on the live translator. I appreciate your honest input, and I'm committed to enhancing the application to meet your expectations.

I understand that the current speed is a concern for you. I'm actively exploring various avenues to improve performance without compromising translation quality. While I'm working on these improvements, your patience is highly appreciated. I am tackling other projects at the moment. I hope I can spare some time for this project again.

**Comment by MotazSabri** [comment]
Appreciate your feedback, @MidnightKittenCat ! In the [latest release](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.8/Hanami.Installer.exe), I've enhanced the speed of both transcription and translation. The response time has  improved, now ranging from 5 to 10 seconds compared to the previous 16-20 seconds.

Your continued support is crucial, and with more users backing the project, I aspire to further enhance its performance. Maintaining the service free relies on this collaborative support. Thank you!
