### ISSUE TITLE
Cant transtlate Turkish

### ISSUE THREAD

**Issue by merolaika** [MotazSabri/Hanami-release#12]
Hello, it cant transtlate english to turkish.

**Comment by MotazSabri** [comment]
> Hello, it cant translate english to Turkish.


Thanks for your comment and sorry for the late response.
I released a [new version](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.8/Hanami.Installer.exe) with numerous upgrades and fixes, including the issue you kindly highlighted.

Looking forward to hearing from you.

**Comment by merolaika** [comment]
thank you so much.

**Comment by merolaika** [comment]
Traceback (most recent call last):
  File "HanamiGUI.py", line 694, in <module>
  File "HanamiGUI.py", line 163, in __init__
  File "HanamiGUI.py", line 630, in conclude_startup
  File "tkinter\__init__.py", line 2345, in __getattr__
AttributeError: '_tkinter.tkapp' object has no attribute 'HanamiCore'

**Comment by MotazSabri** [comment]
@merolaika 
Thanks again for your feedback. 
This issue happened for few users who got some windows updates (namely KB2857650) installed on top of other updates.

I made a small fix for it. Do you mind downloading the [latest setup file ](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.8/Hanami.Installer.exe)again and try installing the application one more time?

Looking forward to hearing from you.
