### ISSUE TITLE
Not working after new update

### ISSUE THREAD

**Issue by jeraldpunx** [MotazSabri/Hanami-release#13]
it listened on the audio but it's blank only, tried reinstall and still not work. :(

**Comment by MotazSabri** [comment]
> it listened on the audio but it's blank only, tried reinstall and still not work. :(

Thanks for your comment, which language have you tried?

**Comment by jeraldpunx** [comment]
thanks for reply, nevermind about my concern, it worked now after switching many language... then suddenly text showed

**Comment by MotazSabri** [comment]
> thanks for reply, nevermind about my concern, it worked now after switching many language... then suddenly text showed

Thanks for your prompt reply.
If you are satisfied with the current quality, feel free to close this issue.
In the latest release, you may notice enhancements in translation gap recovery, increased noise handling, tweaks for Indian and Chinese languages, and a slight improvement in translation speed.

Thanks again for using the app.
