### ISSUE TITLE
Stuck at loading after starting program

### ISSUE THREAD

**Issue by arTEpl4y** [MotazSabri/Hanami-release#14]
Hi,

It's something that also happened 2 versions ago and after the newest update, after starting the program gets stuck at messages like "Uncover words in a byte", "Growth in a byte-sized moment...", "Nearing digital blossom bliss..." and the like.
Now it's not something exclusive to one computer i tested it on both desktop and laptop, (Ryzen cpu+radeon gpu/Intel cpu), both machines running windows 11 with updates.

Basically it's infinite loading for green bar (at the beginning it looks like it is actually loading something but after 10seconds or so the bar speeds up and is looping, goes to max, resets goes to max...)
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/3503c233-3338-41e5-b83e-a5485fa18959)
I attach an image how it looks in task manager.

Is there anything you want me to test or add any info on something? First time opening an issue tried to describe the problem as much as i could.

**Comment by arTEpl4y** [comment]
I also tried uninstalling and running as administrator, didn't help.

**Comment by MotazSabri** [comment]
Thanks for your detailed comment, @arTEpl4y .

I appreciate it if you could do the following:

1. Close the App and terminate all its traces from the task manager.
2. Go to the Windows TEMP folder  (By clicking WINDOWS + R and then type %temp% and enter) and find a folder called HanamiApp.
3.  The file contains the operational contents, delete everything in it (To avoid sharing any personal details) then run the Hanami application.
4. After a while of running the app (Seconds), in the HanamiApp folder, you will find a file called Traces.log. In it, we may find clues as to why this issue happened.
5. If it's a thing you can not manage by yourself, please share the traces.log here so I can try debugging it.

Looking forward to hearing from you.

**Comment by arTEpl4y** [comment]
1. Done
2. Found!
3. There was nothing in the folder
4. Also nothing new appears when booting up the app (even after minutes and spamming refresh)
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/6d5c72a7-54ec-406d-9568-bcdcf0b17512)
5. no file found because #4
Also did reinstall and reboot pc, same things, or rather lack of them in the folder.
Additionally i can say i see one frame of normal UI of the app on start before it goes into infinite green bar loading.

**Comment by MotazSabri** [comment]
Thanks for your response, @arTEpl4y .

This represents an [extended mode ](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.9/HanamiGUI.zip)of the application exclusive to the present version. This link will be removed after the next release. To activate it, run HanamiGUI.exe after extracting the ZIP file contents. Upon launching, a CMD terminal will open, displaying additional debugging details. Kindly report your observations, ensuring no personal information is disclosed in the shared content.

**Comment by arTEpl4y** [comment]
Thanks for response @MotazSabri 
I kindly report observations: lack of them...
Downloaded and extracted extended mode of the app and run it on both desktop and laptop:
- On laptop:
 Run for few minutes (looped as on desktop) then got terminated by windows defender and hanamiapp.exe got removed, when extracting again i get error 0x800700E1.
- On desktop
It tries to start like before:
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/64bda47b-0a00-4575-960d-3d57640c8951)
,but if i close the bar with [X] i get some things in command line:
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/a4df80d1-1b79-47c8-9052-3200bf9aa495)
Maybe it has something to do with Windows Defender killing sus processes?

**Comment by MotazSabri** [comment]
Thank you for your comprehensive reply.

Regarding the laptop:
The error code 0x800700E1 appears to be linked to a Windows Defender issue, as you astutely pointed out. The application operates transparently, capturing audio in chunks and interacting with online transcription and translation services for results. It seems that Windows Defender might be triggering a false alarm, leaving the decision to trust the app in the hands of the user. Feel free to inquire about any specific steps if there are concerns.

Concerning the desktop:
I'm keen to examine the CMD output before you close the application, as it will display a list of available devices for initiating the translation. Apologies for the straightforward question, but can you confirm the presence of speakers or a sound card on the machine?

**Comment by arTEpl4y** [comment]
The desktop:
The CMD output was only the errors, nothing appeared in CMD during infinite loading.
No problem with straightforwardness, users can sometimes be stupid (i sure hope i am not one atm).
I do have speakers and soundcard, at least i can confirm nothing changed hardware wise between the updates (before the update the program was working flawlessly).
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/f5da7c78-52f8-4867-9e70-77b0f0332e40)
The laptop:
I will try to tackle defender now.

**Comment by arTEpl4y** [comment]
From laptop:
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/9ab3f6ef-8e95-47dd-90dc-03541b597dd4)
Also nothing apppears in CMD output after few minutes of running the program, only when closing the app when the green bar becomes more "fluid" (less laggy, also noticed when trying to move window around at first it's laggy after some time [1 minute] it becomes more fluid to move, much like the green bar)

**Comment by arTEpl4y** [comment]
Got something this time:
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/ad5a0ecf-730f-4681-a21c-9c9c8b04839c)
Probably issue?: "UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-40: character maps to <undefined>"
also i will attach files from temporary folder, i don't see any sensitive info besides my username therefore i will attach the files
[Traces.log](https://github.com/MotazSabri/Hanami-release/files/14339495/Traces.log)
"logging.ini":
`[loggers]
keys=root

[handlers]
keys=fileHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=INFO
handlers=fileHandler

[handler_fileHandler]keyw
class=FileHandler
level=INFO
formatter=simpleFormatter
args=("C:\\Users\\arTE\\AppData\\Local\\Temp\\HanamiApp\\Traces.log",)

[formatter_simpleFormatter]
format=%(asctime)s %(name)s - %(levelname)s:%(message)s`

**Comment by MotazSabri** [comment]
Thanks
This should not block the progress bar from disappearing as the logging is happening independently from the main process. Did anything else appear after the logger error? Maybe something like

![image](https://github.com/MotazSabri/Hanami-release/assets/72955854/2f08f905-6e2a-465c-8efe-c5ca98b72d22)


In my case the application moved few steps forward and started capturing data.
If you keep the app running, will the last line in the traces.log file be as you shared in your previous message?

**Comment by arTEpl4y** [comment]
Unfortunately nothing appears like on your output:
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/2b4b23ad-c544-467d-933e-ff4a7e95d2b4)
It gets to looped progress bar and nothing else happens.
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/184e133d-4d1e-4d9a-9553-232f5809f8a0)
Next output only appears after i close the app manually.
But seemingly in traces.log there are errors getting catched after i close the application, take a look: 
[Traces.log](https://github.com/MotazSabri/Hanami-release/files/14339827/Traces.log)

**Comment by arTEpl4y** [comment]
From laptop the same thing is happening, but some lines are not appearing (mainly logging error ones), i attach screenshots below:
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/958c7567-23c4-42fd-a90e-f71600938ea3)
I will also attach traces.log file, cause it differs from desktop one: 
[Traces.log](https://github.com/MotazSabri/Hanami-release/files/14339918/Traces.log)
Ultimately i think it might be network related issue, was there anything that changed in the last 3 updates, that made only the last one work and connect properly? I tried uing VPN to tunnel through different country but no luck, same messages. I will also add that nothing has changed in my network setup between the versions.

**Comment by MotazSabri** [comment]
Thank you for providing detailed information and screenshots @arTEpl4y . I appreciate your understanding regarding the technical aspects.

Upon startup, the application initializes its connection with translation servers. Based on the Traces.log, the application successfully establishes its initial connection with DeepL. However, it encounters difficulties, specifically freezing, when attempting to connect to Google services. It's worth noting that no network-related modifications have been made in this part of the code.

To address this issue, I have introduced a timeout of 10 seconds. My hypothesis is that this may be related to an initialization problem. With the timeout in place, I hope that after the progress bar disappears, both backends can be used seamlessly.

Could you kindly test the [modified executables ](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.9/HanamiGUI.zip)and provide feedback on whether this resolves the issue?

Thank you for your time and cooperation.

**Comment by arTEpl4y** [comment]
@MotazSabri Thank for providing test version! Yes, i used the modified exec on laptop and it allowed the program to initialize correctly.
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/e4b1d396-e5c3-455b-be00-804381be0a55)
It seems to correctly pick up sound and detect if there is too much ambient noise as well.
Although it seems the translation itself is not working, the transcribe appears to work correctly.

**Comment by arTEpl4y** [comment]
If i may add:
![image](https://github.com/MotazSabri/Hanami-release/assets/28930316/2770e049-dad2-4341-8095-10df5dc353d1)
watch out for the size of the log file, it grew to 345MB after using the modified exec for around 5 minutes.

**Comment by MotazSabri** [comment]
Thank you for your valuable feedback @arTEpl4y . Please note that the current version is a debugging release, and I plan to provide an urgent update for you before the official release once we finalize a permanent fix. We will reduce the size of this log file soon.

The application utilizes its dedicated portable browser, located in the HanamiAux folder under HanamiAux\GuidedLibs\App\Chrome-bin. This configuration has been consistent since the earliest release of the application. However, there is a possibility that it might have been mistakenly blacklisted, preventing it from accessing the internet. It seems like there may be a restriction on its internet access.

Could you please check if there have been any recent security updates affecting this executable (also check chromedriver.exe) ? Additionally, consider opening the executable and trying to access sites such as Google Translate and DeepL to help identify and troubleshoot the issue.

Your cooperation in this matter is highly appreciated.

**Comment by arTEpl4y** [comment]
Honestly i don't know about any recent security updates, but even with completely disabled windows defender and firewall i fail to get the translation going.
On the other hand, the standalone chrome browser works perfectly fine, connecting to deepl and google translate. 
If you want me to do anything else in terms of troubleshooting please let me know.

**Comment by arTEpl4y** [comment]
Also tried changing internet source (instead of usual ISP, tethered through mobile data), same thing happens. Applications starts, is able to transcribe but doesn't get any translation back from DeepL/GTranslate.

**Comment by MotazSabri** [comment]
Sorry for the delayed response. @arTEpl4y 
I tried to enable the Standalone browser to post its content into a file in [this version](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.9/HanamiGUI.zip). 

After running this version there will be 2 files generated next to the executable: deepl.txt and GTranslate.txt. Please share them here. The file will reflect either the warm up results or the results from the audio from your speakers.

**Comment by arTEpl4y** [comment]
I come with great news, the version you posted just now works! (as in translates, but from what i noticed from 2 minutes of using it the quality of translation tanked down)
Below i attach requested files:
[deepl.txt](https://github.com/MotazSabri/Hanami-release/files/14344985/deepl.txt)
[GTranslate.txt](https://github.com/MotazSabri/Hanami-release/files/14344986/GTranslate.txt)

**Comment by MotazSabri** [comment]
@arTEpl4y That is a great news. Thanks for confirming. I will create a new release for the new fixes.

But before that, regarding the Translation, may I know what languages are you using as input as output ? Do you think it's a transcription issue or translation issue?

**Comment by arTEpl4y** [comment]
@MotazSabri Japanese as input, English as output. It might honestly be transcription issue, also i think im getting the message about ambient noise more often compared to previous version, i almost never have noticed it (was it even there?)

**Comment by MotazSabri** [comment]
Thank you for sharing your feedback, @arTEpl4y 

In the earlier version, the application displayed blank translations in the presence of high background noise, even when no audible noise was detected due to speech-to-text sensitivity. In the current release, noise reduction has been implemented, along with a notification to alert the user if the noise level is high or if there is a mismatch between the selected language and the spoken language. I think this is why you may see this notification recently.

While I acknowledge that the current quality may not be something to boast about, it's a work in progress. With valuable tips and encouragement from users like you, I am committed to continuously improving.

I have just pushed a [new release](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.9/Hanami.Installer.exe). If you find that it resolves the issue of infinite loading, kindly consider closing this issue. Your ongoing support is greatly appreciated.

**Comment by arTEpl4y** [comment]
@MotazSabri
Yup! Tested the new release on both laptop and desktop. Application does work and both transcribes and translates properly!
I would like to thank you very much for spending this much time to fix which virtually affected probably only me, or very few people silent about the issue. I use the app almost daily to watch stuff online, mainly in Japanese. I will continue to use and report anything i can to make the app better!
