### ISSUE TITLE
Program asks to update to latest version but there is no new version to update to.

### ISSUE THREAD

**Issue by SmolYui** [MotazSabri/Hanami-release#15]
![image](https://github.com/MotazSabri/Hanami-release/assets/95811710/d1e7d972-f31b-4b88-b0b9-3f61aa01cde4)
> Time to update Hanami, please visit our site to get the latest version.

reinstall doesn't work.

**Comment by jeraldpunx** [comment]
also add auto-update instead of downloading in git...

**Comment by MotazSabri** [comment]
> ![image](https://private-user-images.githubusercontent.com/95811710/316333173-d1e7d972-f31b-4b88-b0b9-3f61aa01cde4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzY1NDgsIm5iZiI6MTcxMTMzNjI0OCwicGF0aCI6Ii85NTgxMTcxMC8zMTYzMzMxNzMtZDFlN2Q5NzItZjMxYi00Yjg4LWIwYjktM2Y2MWFhMDFjZGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAzMTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZDEwMGU3ZmFjZTA0MGY2YjU0OWM0OTJkNWYyODdiODMyYWJmODc4OTUwNjVkODM1NWRkM2EzYWI5Zjc5M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kAcLYgag7xuNv_QCe8WMJQWAARO4lcBxfz_zmBCMOic)
> 
> > Time to update Hanami, please visit our site to get the latest version.
> 
> reinstall doesn't work.
@SmolYui 
Thanks for your kind follow-up. There was an issue in the versioning server and it was fixed. 
Please get the latest Hanami Version and confirm if this issue is fixed on your side.

**Comment by MotazSabri** [comment]
> also add auto-update instead of downloading in git...


Thank you, @jeraldpunx , for the suggestion! It's a great idea and something I'm keeping in mind for future updates. However, integrating it poses a challenge as the software relies on specific Windows updates, and selectively auto-downloading could impact application stability. For now, users are required to uninstall and install the new app to ensure smooth operation. Appreciate your understanding!

**Comment by SmolYui** [comment]
Seems to be working, thank you!

**Comment by MotazSabri** [comment]
Thanks for confirming.
