### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by jeraldpunx** [MotazSabri/Hanami-release#21]
title says

**Comment by MotazSabri** [comment]
> title says

Thank you for bringing this to my attention, @jeraldpunx and I apologize for the delayed response.

It seems one of the free translation backends recently updated its gateway, and I've just pushed a new version to accommodate those changes.

Could you please check if this resolves the issue? If everything works as expected, feel free to close the issue.

**Comment by jeraldpunx** [comment]
it works thanks again
