### ISSUE TITLE
Languages withoout star symbol not working at all

### ISSUE THREAD

**Issue by VVinchi** [MotazSabri/Hanami-release#3]

**Comment by MotazSabri** [comment]
Thanks for your follow-up.
As mentioned in the project description, some languages are more capable than others. We use Deepl and Google Translate free services. The quality of the translation is directly related to those providers' translations. We marked the languages with relatively stronger translations with a star to indicate their strength.

We hope to use stronger translations backends to ensure better translation quality on the long run.
