### ISSUE TITLE
Hanami is offline

### ISSUE THREAD

**Issue by AlimentativeCerebral** [MotazSabri/Hanami-release#4]
Hi,

I downloaded and installed Hanami but it says Hanami is offline. Is it possible to resolve this?

Best Regards,
Cerebral

![image](https://user-images.githubusercontent.com/130181128/234947766-b089d82f-99a0-43df-82ad-0eaab6ce0a2c.png)

**Comment by MotazSabri** [comment]
Thanks for your feedback.
This message only appears if the applicant does not have access to the internet. Can you check if there is internet connectivity or maybe the windows have blocked the app from accessing the internet?

Hope this help.
