### ISSUE TITLE
Option for transcribe only - transcribe to text?

### ISSUE THREAD

**Issue by FlowZenMaster** [MotazSabri/Hanami-release#5]
I've been looking for a simple tool that takes system audio and transcribes into a text file on a streaming basis. It seems like this tool can do it, but I can't figure out how to get it to NOT translate. Looking for english->english essentially, but written to a file. There is a lot of use for a free program that can accomplish this.

**Comment by MotazSabri** [comment]
> I've been looking for a simple tool that takes system audio and transcribes into a text file on a streaming basis. It seems like this tool can do it, but I can't figure out how to get it to NOT translate. Looking for english->english essentially, but written to a file. There is a lot of use for a free program that can accomplish this.

Thanks for your remark.
The app transcribes the audio into text as you kindly highlighted but we don't save it or keep any copy for it to maintain user privacy.

As we mentioned in the project Readme, we used Google API for the transcription. You can give it a try or try a more modern alternative such as OpenAI Whipser.

Hope this helps.

**Comment by MotazSabri** [comment]
@FlowZenMaster 
Appreciate your input! In response to your request, I've incorporated language transcription in the [latest release](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.8/Hanami.Installer.exe). While it currently doesn't save text to a file, it can assist users with hearing difficulties by enabling them to read meeting/video content through the Transcribe service.

Looking ahead, if there's substantial user support, I might explore creating individual transcriptions with speaker identification. However, this could be a challenging endeavor, particularly if I aim to maintain the app as a free resource. Your support is invaluable!

**Comment by SmolYui** [comment]
expanding on this, a feature where it shows both the transcription and the translation would be useful for me.

**Comment by MotazSabri** [comment]
> expanding on this, a feature where it shows both the transcription and the translation would be useful for me.


Thanks for your input, @SmolYui !

 I've implemented a new feature called Mixture, which combines both translation and transcription functionalities. However, due to the fixed size of the application, selecting the Mixture service causes the font size to decrease. The font size returns to normal when reverting back to the original services (Translate and Transcribe).

**Comment by SmolYui** [comment]
@MotazSabri Excellent! Thank you for you quick implimentation! Although, the service is labelled "Mixt**ru**e" instead of "Mixture". ^w^

**Comment by MotazSabri** [comment]
> @MotazSabri Excellent! Thank you for you quick implimentation! Although, the service is labelled "Mixt**ru**e" instead of "Mixture". ^w^

Thanks for your feedback, @SmolYui .
I created a hotfix setup for this and pushed it as an intermediate release. You may get it from [here](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release1.9/Hanami.Installer.exe).
