### ISSUE TITLE
Hello, vírus?

### ISSUE THREAD

**Issue by odorizzioficial** [MotazSabri/Hanami-release#6]
Hello friend, is there any virus in your program? Or is it a false positive? I always check programs before downloading from virustotal
![2023-05-21_02-47](https://github.com/MotazSabri/Hanami-release/assets/110546717/575e5d5c-bfbb-4e9d-b04e-3a6c8c69f986)

**Comment by MotazSabri** [comment]
Thanks for your kind remark,
The app does not have any malicious or harmful components. It captures the computer audio signal and uses well-known APIs to transcribe and translate the text.

Capturing audio is a low-level task that requires access to operating system components. such access may be considered suspicious by some antiviruses. 

For your reference, the application stores the audio chunks for a few seconds to process them and then deletes them to maintain user privacy. They are temporarily stored in this path:

`C:\Users\[YOUR USER NAME]\AppData\Local\Temp\HanamiApp`

I hope this clarifies the workflow of Hanami.

**Comment by odorizzioficial** [comment]
Alright buddy, thanks a lot for clarifying
